# Generated by Django 6.0.6 on 2026-06-17 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim_id', models.CharField(max_length=32, unique=True, verbose_name='UYAP Birim No')),
                ('ad', models.CharField(max_length=255, verbose_name='Birim Adı')),
                ('turu1', models.CharField(blank=True, max_length=8, verbose_name='birimTuru1')),
                ('turu2', models.CharField(blank=True, max_length=8, verbose_name='birimTuru2')),
                ('turu3', models.CharField(blank=True, max_length=8, verbose_name='birimTuru3')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Birim',
                'verbose_name_plural': 'Birimler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Taraf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('gercek', 'Gerçek Kişi'), ('tuzel', 'Tüzel Kişi')], max_length=8)),
                ('ad', models.CharField(blank=True, max_length=120)),
                ('soyad', models.CharField(blank=True, max_length=120)),
                ('tckn', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='TCKN')),
                ('unvan', models.CharField(blank=True, max_length=400, verbose_name='Unvan / Şirket Adı')),
                ('mersis_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='MERSIS No')),
                ('vergi_no', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='Vergi No')),
                ('e_tebligat_adresi', models.CharField(blank=True, max_length=255, verbose_name='E-Tebligat Adresi')),
                ('kep_adresi', models.CharField(blank=True, max_length=255, verbose_name='KEP Adresi')),
                ('adres', models.TextField(blank=True)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taraf',
                'verbose_name_plural': 'Taraflar',
            },
        ),
        migrations.CreateModel(
            name='Vekil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120)),
                ('soyad', models.CharField(blank=True, max_length=120)),
                ('tckn', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='TCKN')),
                ('baro_sicil', models.CharField(blank=True, max_length=40, verbose_name='Baro Sicil No')),
                ('adres', models.TextField(blank=True)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vekil',
                'verbose_name_plural': 'Vekiller',
            },
        ),
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya_id', models.CharField(max_length=255, unique=True, verbose_name='UYAP Dosya Kimliği')),
                ('yil', models.PositiveIntegerField(verbose_name='Dosya Yılı')),
                ('sira_no', models.PositiveIntegerField(verbose_name='Dosya No')),
                ('dosya_no', models.CharField(max_length=20, verbose_name='Dosya No (ham)')),
                ('durum_kod', models.IntegerField(choices=[(0, 'Açık'), (1, 'Kapalı')], default=0)),
                ('durum', models.CharField(blank=True, max_length=20)),
                ('tur_kod', models.IntegerField(choices=[(0, 'Esas'), (1, 'Talimat')], default=0)),
                ('tur', models.CharField(blank=True, max_length=40)),
                ('acilis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Açılış Tarihi')),
                ('is_dava_dosyasi_acilmis', models.BooleanField(default=False)),
                ('son_senkron', models.DateTimeField(auto_now=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosyalar', to='icra_models.birim')),
            ],
            options={
                'verbose_name': 'Dosya',
                'verbose_name_plural': 'Dosyalar',
                'ordering': ['-acilis_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='DosyaTaraf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('alacakli', 'Alacaklı'), ('borclu', 'Borçlu')], max_length=10)),
                ('sira', models.PositiveIntegerField(default=0)),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taraf_baglari', to='icra_models.dosya')),
                ('taraf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosya_baglari', to='icra_models.taraf')),
                ('vekil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temsil_baglari', to='icra_models.vekil')),
            ],
            options={
                'verbose_name': 'Dosya Tarafı',
                'verbose_name_plural': 'Dosya Tarafları',
                'ordering': ['dosya', 'rol', 'sira'],
            },
        ),
        migrations.AddField(
            model_name='dosya',
            name='taraflar',
            field=models.ManyToManyField(related_name='dosyalar', through='icra_models.DosyaTaraf', to='icra_models.taraf'),
        ),
        migrations.AddConstraint(
            model_name='dosya',
            constraint=models.UniqueConstraint(fields=('birim', 'yil', 'sira_no', 'tur_kod'), name='uq_dosya_kunye'),
        ),
        migrations.AddConstraint(
            model_name='dosyataraf',
            constraint=models.UniqueConstraint(fields=('dosya', 'taraf', 'rol'), name='uq_dosya_taraf_rol'),
        ),
    ]
