# Generated by Django 6.0.6 on 2026-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='dosya_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='UYAP Dosya Kimliği (oturumluk)'),
        ),
    ]
