# Generated by Django 6.0.6 on 2026-07-10 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0002_alter_dosya_dosya_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim_evrak_no', models.PositiveIntegerField(db_index=True, verbose_name='Birim Evrak No')),
                ('evrak_turu', models.CharField(blank=True, max_length=64, verbose_name='Evrak Türü')),
                ('evrak_tip', models.CharField(blank=True, max_length=16, verbose_name='Evrak Tipi')),
                ('aciklama', models.CharField(blank=True, max_length=500, verbose_name='Açıklama')),
                ('evrak_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Evrak Tarihi')),
                ('mime_turu', models.CharField(blank=True, max_length=64, verbose_name='MIME Türü')),
                ('boyut', models.PositiveIntegerField(default=0, verbose_name='Boyut (bayt)')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('dosya_yolu', models.CharField(max_length=500, verbose_name='Diskteki Dosya Yolu')),
                ('degisebilir', models.BooleanField(default=False, verbose_name='Değişebilir Evrak')),
                ('indirilme_zamani', models.DateTimeField(auto_now_add=True)),
                ('son_erisim_zamani', models.DateTimeField(auto_now=True)),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evraklar', to='icra_models.dosya')),
                ('ust_evrak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ekler', to='icra_models.evrak')),
            ],
            options={
                'verbose_name': 'Evrak',
                'verbose_name_plural': 'Evraklar',
                'ordering': ['dosya', 'birim_evrak_no'],
                'constraints': [models.UniqueConstraint(fields=('dosya', 'birim_evrak_no'), name='uq_dosya_evrak')],
            },
        ),
    ]
