# Generated by Django 6.0.6 on 2026-07-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0003_evrak'),
    ]

    operations = [
        migrations.AddField(
            model_name='birim',
            name='yargi_turu',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Yargı Türü Kodu'),
        ),
        migrations.AlterField(
            model_name='dosya',
            name='durum_kod',
            field=models.IntegerField(choices=[(0, 'Açık'), (1, 'Kapalı'), (7, 'Karara Çıkmış'), (29, 'İstinafta')], default=0),
        ),
        migrations.AlterField(
            model_name='dosya',
            name='tur_kod',
            field=models.IntegerField(choices=[(0, 'Esas'), (1, 'Talimat'), (14, 'Hukuk Değişik İş Dosyası'), (15, 'Hukuk Dava Dosyası')], default=0),
        ),
        migrations.CreateModel(
            name='HukukDavaDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dava_acilis_turu', models.CharField(blank=True, max_length=120)),
                ('dava_turleri', models.CharField(blank=True, max_length=500)),
                ('ilgili_dosya_listesi', models.CharField(blank=True, max_length=500)),
                ('ilgili_dava_listesi', models.CharField(blank=True, max_length=500)),
                ('ilgili_seri_dava_listesi', models.CharField(blank=True, max_length=500)),
                ('birlesen_dosya_listesi', models.CharField(blank=True, max_length=500)),
                ('durusma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('basvuruya_birakilma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('dosya', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hukuk_detay', to='icra_models.dosya')),
            ],
            options={
                'verbose_name': 'Hukuk Dava Detayı',
                'verbose_name_plural': 'Hukuk Dava Detayları',
            },
        ),
        migrations.CreateModel(
            name='IcraTakipDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takibin_turu', models.CharField(blank=True, max_length=8)),
                ('takibin_turu_aciklama', models.CharField(blank=True, max_length=120)),
                ('takibin_sekli', models.CharField(blank=True, max_length=8)),
                ('takibin_sekli_aciklama', models.CharField(blank=True, max_length=255)),
                ('takibin_yolu', models.CharField(blank=True, max_length=8)),
                ('takibin_yolu_aciklama', models.CharField(blank=True, max_length=120)),
                ('alacak_kalemi_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('alacak_kalemi_faiz', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('takip_sonrasi_masraf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vekalet_ucreti', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tahsil_harci', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('yapilmis_tahsilat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('dosya', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icra_detay', to='icra_models.dosya')),
            ],
            options={
                'verbose_name': 'İcra Takip Detayı',
                'verbose_name_plural': 'İcra Takip Detayları',
            },
        ),
        migrations.CreateModel(
            name='SenkronKapsami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yargi_turu', models.PositiveSmallIntegerField(verbose_name='Yargı Türü Kodu')),
                ('yargi_birimi_kod', models.CharField(blank=True, max_length=8, verbose_name='Yargı Birimi Kodu (tablo)')),
                ('aktif', models.BooleanField(default=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Senkron Kapsamı',
                'verbose_name_plural': 'Senkron Kapsamları',
                'constraints': [models.UniqueConstraint(fields=('yargi_turu', 'yargi_birimi_kod'), name='uq_senkron_kapsami')],
            },
        ),
        migrations.CreateModel(
            name='YargiBirimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yargi_turu', models.PositiveSmallIntegerField(db_index=True, verbose_name='Yargı Türü Kodu')),
                ('kod', models.CharField(max_length=8, verbose_name='Birim Türü Kodu (tablo)')),
                ('ad', models.CharField(max_length=120, verbose_name='Birim Türü Adı')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yargı Birimi',
                'verbose_name_plural': 'Yargı Birimleri',
                'ordering': ['yargi_turu', 'ad'],
                'constraints': [models.UniqueConstraint(fields=('yargi_turu', 'kod'), name='uq_yargi_birimi')],
            },
        ),
    ]
