# Generated by Django 6.0.6 on 2026-07-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0004_birim_yargi_turu_alter_dosya_durum_kod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyataraf',
            name='rol',
            field=models.CharField(choices=[('alacakli', 'Alacaklı'), ('borclu', 'Borçlu'), ('davaci', 'Davacı'), ('davali', 'Davalı')], max_length=10),
        ),
    ]
