# Generated by Django 6.0.6 on 2026-07-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0005_alter_dosyataraf_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyataraf',
            name='rol',
            field=models.CharField(choices=[('alacakli', 'Alacaklı'), ('borclu', 'Borçlu'), ('davaci', 'Davacı'), ('davali', 'Davalı'), ('sanik', 'Sanık'), ('musteki', 'Müşteki'), ('ucuncu sahis', 'Üçüncü Şahıs'), ('hissedar', 'Hissedar'), ('tasfiye memuru', 'Tasfiye Memuru'), ('basvurucu', 'Başvurucu'), ('diger taraf', 'Diğer Taraf')], max_length=20),
        ),
    ]
