# Generated by Django 6.0.5 on 2026-07-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0006_alter_dosyataraf_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='durum',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dosya',
            name='tur',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
