# Generated by Django 6.0.6 on 2026-07-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0008_alter_dosyataraf_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='dosya_no',
            field=models.CharField(max_length=255, verbose_name='Dosya No (ham)'),
        ),
    ]
