# Generated by Django 6.0.6 on 2026-07-12 00:32
# Elle düzenlendi: AddField önce, sonra veri taşıma (RunPython), sonra
# RemoveField — canlı DB'de zaten 16 satırda vekil_id doluydu (kullanıcı
# bulgusu, 2026-07-11: birden fazla vekil olduğunda eskiden yalnız ilki
# kaydediliyordu); düz Remove+Add sırası bu veriyi sessizce silerdi.

from django.db import migrations, models


def vekil_id_yi_m2m_ye_tasi(apps, schema_editor):
    DosyaTaraf = apps.get_model("icra_models", "DosyaTaraf")
    for dt in DosyaTaraf.objects.exclude(vekil__isnull=True):
        dt.vekiller.add(dt.vekil_id)


def geri_al(apps, schema_editor):
    # Geri dönüşte M2M'de birden fazla vekil varsa yalnız ilki vekil_id'ye
    # taşınır (tekil FK'nin doğası gereği kayıp kaçınılmaz).
    DosyaTaraf = apps.get_model("icra_models", "DosyaTaraf")
    for dt in DosyaTaraf.objects.all():
        ilk = dt.vekiller.first()
        if ilk:
            dt.vekil_id = ilk.id
            dt.save(update_fields=["vekil"])


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0009_alter_dosya_dosya_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosyataraf',
            name='vekiller',
            field=models.ManyToManyField(blank=True, related_name='temsil_baglari', to='icra_models.vekil'),
        ),
        migrations.RunPython(vekil_id_yi_m2m_ye_tasi, geri_al),
        migrations.RemoveField(
            model_name='dosyataraf',
            name='vekil',
        ),
    ]
