# Generated by Django 6.0.5 on 2026-07-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0010_remove_dosyataraf_vekil_dosyataraf_vekiller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='tur_kod',
            field=models.IntegerField(choices=[(0, 'Esas'), (1, 'Talimat'), (14, 'Hukuk Değişik İş Dosyası'), (15, 'Hukuk Dava Dosyası'), (16, 'CBS Soruşturma Dosyası')], default=0),
        ),
    ]
