# Generated by Django 6.0.5 on 2026-07-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0011_alter_dosya_tur_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosyataraf',
            name='kesinlesme_durumu',
            field=models.CharField(blank=True, choices=[('kesinlesmedi', 'Kesinleşmedi'), ('kesinlesti', 'Kesinleşti'), ('kismen_kesinlesti', 'Kısmen Kesinleşti'), ('itiraz', 'İtiraz'), ('konkordato', 'Konkordato'), ('iflas', 'İflas')], max_length=20, verbose_name='Kesinleşme Durumu'),
        ),
    ]
