# Generated by Django 6.0.6 on 2026-08-03 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0012_dosyataraf_kesinlesme_durumu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TebligatBarkod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim_evrak_no', models.PositiveIntegerField(db_index=True, verbose_name='Birim Evrak No')),
                ('evrak_aciklama', models.CharField(blank=True, max_length=500, verbose_name='Evrak Açıklaması')),
                ('evrak_tarihi', models.CharField(blank=True, max_length=40, verbose_name='Evrak Tarihi')),
                ('barkod', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='PTT Barkod No')),
                ('elektronik_tebligat', models.BooleanField(default=False, verbose_name="Elektronik Tebligat (PTT'de takip yok)")),
                ('ptt_durumu', models.CharField(blank=True, max_length=255, verbose_name='PTT Durumu')),
                ('son_islem_tarihi', models.CharField(blank=True, max_length=40, verbose_name='Son İşlem Tarihi')),
                ('ham_yanit', models.JSONField(blank=True, null=True, verbose_name='PTT Ham Yanıt')),
                ('tebligat_mazbatasi_var', models.BooleanField(default=False, verbose_name='Tebliğ Mazbatası Dosyaya Dönmüş')),
                ('tebligat_mazbatasi_aciklama', models.CharField(blank=True, max_length=500, verbose_name='Tebliğ Mazbatası Açıklaması')),
                ('kapali_tebligat_mazbatasi_var', models.BooleanField(default=False, verbose_name='Kapalı Tebliğ Mazbatası Var')),
                ('sorgu_zamani', models.DateTimeField(auto_now=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tebligat_barkodlari', to='icra_models.dosya')),
            ],
            options={
                'verbose_name': 'Tebligat Barkod Sorgusu',
                'verbose_name_plural': 'Tebligat Barkod Sorguları',
                'ordering': ['-sorgu_zamani'],
                'constraints': [models.UniqueConstraint(fields=('dosya', 'birim_evrak_no'), name='uq_dosya_tebligat_barkod')],
            },
        ),
    ]
