# Generated by Django 6.0.6 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0013_tebligatbarkod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tebligatbarkod',
            name='tebligat_turu',
            field=models.CharField(blank=True, max_length=60, verbose_name='Tebligat Türü'),
        ),
    ]
