# Generated by Django 6.0.5 on 2026-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0014_tebligatbarkod_tebligat_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosyataraf',
            name='tebligat_durumu',
            field=models.CharField(blank=True, choices=[('teblig_edildi', 'Tebliğ Edildi'), ('iade', 'İade'), ('dagitimda', 'Dağıtımda'), ('mernis_yok', 'Mernis Yok'), ('yeniden_teblig_talep_edilecek', 'Yeniden Tebliğ Talep Edilecek'), ('yeniden_teblig_talep_edildi', 'Yeniden Tebliğ Talep Edildi')], max_length=30, verbose_name='Tebliğ Durumu'),
        ),
        migrations.AlterField(
            model_name='dosyataraf',
            name='kesinlesme_durumu',
            field=models.CharField(blank=True, choices=[('kesinlesti', 'Kesinleşti'), ('kesinlesme_bekliyor', 'Kesinleşme Bekliyor'), ('itiraz', 'İtiraz'), ('konkordato', 'Konkordato'), ('vefat', 'Vefat'), ('vasi', 'Vasi')], max_length=20, verbose_name='Kesinleşme Durumu'),
        ),
    ]
