# Generated by Django 6.0.5 on 2026-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0015_dosyataraf_tebligat_durumu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResmiTatil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(unique=True, verbose_name='Tarih')),
                ('aciklama', models.CharField(blank=True, max_length=120, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Resmi Tatil',
                'verbose_name_plural': 'Resmi Tatiller',
                'ordering': ['tarih'],
            },
        ),
        migrations.AddField(
            model_name='dosyataraf',
            name='itiraz_edildi_mi',
            field=models.BooleanField(default=False, verbose_name='İtiraz Edildi mi'),
        ),
        migrations.AddField(
            model_name='dosyataraf',
            name='itiraz_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='İtiraz Tarihi'),
        ),
    ]
