# Generated by Django 6.0.5 on 2026-08-04 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0016_resmitatil_dosyataraf_itiraz_edildi_mi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tebligatbarkod',
            name='borclu',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'borclu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tebligat_barkodlari', to='icra_models.dosyataraf'),
        ),
    ]
