# Generated by Django 6.0.5 on 2026-08-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0017_tebligatbarkod_borclu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tebligatbarkod',
            name='yeniden_teblig_talep_edildi',
            field=models.BooleanField(default=False, verbose_name='Yeniden Tebliğ Talebi Gönderildi mi'),
        ),
    ]
