# Generated by Django 6.0.5 on 2026-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icra_models', '0018_tebligatbarkod_yeniden_teblig_talep_edildi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tebligatbarkod',
            name='t212_kategori',
            field=models.CharField(blank=True, max_length=255, verbose_name='21/2 Tarama Sonucu'),
        ),
        migrations.AddField(
            model_name='tebligatbarkod',
            name='t212_mernis_adresi',
            field=models.CharField(blank=True, max_length=500, verbose_name='21/2 Mernis Adresi'),
        ),
        migrations.AddField(
            model_name='tebligatbarkod',
            name='t212_tarandi_zamani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='21/2 Son Tarama Zamanı'),
        ),
        migrations.AddField(
            model_name='tebligatbarkod',
            name='t212_teblig_adresi',
            field=models.CharField(blank=True, max_length=500, verbose_name='21/2 Tebligat Adresi'),
        ),
    ]
